<%
Function getCurrency(fWidth,fName,fDefault)

	getCurrency = "<select name=""" & fName & """ id=""" & fName & """ class=""oText"" style=""width:" & fWidth & "px;"" onChange=""doChange();"">" & vbCrLf & _
				vbTab & "<option></option>" & vbCrLf & _
				vbTab & "<option value=""AFA""" & getDefault(0,fDefault,"AFA") & ">AFA - Afghanistan Afghani</option>" & vbCrLf & _
				vbTab & "<option value=""ALL""" & getDefault(0,fDefault,"ALL") & ">ALL - Albanian Lek</option>" & vbCrLf & _
				vbTab & "<option value=""DZD""" & getDefault(0,fDefault,"DZD") & ">DZD - Algerian Dinar</option>" & vbCrLf & _
				vbTab & "<option value=""ADF""" & getDefault(0,fDefault,"ADF") & ">ADF - Andorran Franc</option>" & vbCrLf & _
				vbTab & "<option value=""ADP""" & getDefault(0,fDefault,"ADP") & ">ADP - Andorran Peseta</option>" & vbCrLf & _
				vbTab & "<option value=""AON""" & getDefault(0,fDefault,"AON") & ">AON - Angolan New Kwanza</option>" & vbCrLf & _
				vbTab & "<option value=""ARS""" & getDefault(0,fDefault,"ARS") & ">ARS - Argentine Peso</option>" & vbCrLf & _
				vbTab & "<option value=""AWG""" & getDefault(0,fDefault,"AWG") & ">AWG - Aruban Florin</option>" & vbCrLf & _
				vbTab & "<option value=""AUD""" & getDefault(0,fDefault,"AUD") & ">AUD - Australian Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""ATS""" & getDefault(0,fDefault,"ATS") & ">ATS - Austrian Schilling</option>" & vbCrLf & _
				vbTab & "<option value=""BSD""" & getDefault(0,fDefault,"BSD") & ">BSD - Bahamian Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""BHD""" & getDefault(0,fDefault,"BHD") & ">BHD - Bahraini Dinar</option>" & vbCrLf & _
				vbTab & "<option value=""BDT""" & getDefault(0,fDefault,"BDT") & ">BDT - Bangladeshi Taka</option>" & vbCrLf & _
				vbTab & "<option value=""BBD""" & getDefault(0,fDefault,"BBD") & ">BBD - Barbados Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""BEF""" & getDefault(0,fDefault,"BEF") & ">BEF - Belgian Franc</option>" & vbCrLf & _
				vbTab & "<option value=""BZD""" & getDefault(0,fDefault,"BZD") & ">BZD - Belize Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""BMD""" & getDefault(0,fDefault,"BMD") & ">BMD - Bermudian Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""BTN""" & getDefault(0,fDefault,"BTN") & ">BTN - Bhutan Ngultrum</option>" & vbCrLf & _
				vbTab & "<option value=""BOB""" & getDefault(0,fDefault,"BOB") & ">BOB - Bolivian Boliviano</option>" & vbCrLf & _
				vbTab & "<option value=""BWP""" & getDefault(0,fDefault,"BWP") & ">BWP - Botswana Pula</option>" & vbCrLf & _
				vbTab & "<option value=""BRL""" & getDefault(0,fDefault,"BRL") & ">BRL - Brazilian Real</option>" & vbCrLf & _
				vbTab & "<option value=""GBP""" & getDefault(0,fDefault,"GBP") & ">GBP - British Pound</option>" & vbCrLf & _
				vbTab & "<option value=""BND""" & getDefault(0,fDefault,"BND") & ">BND - Brunei Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""BGL""" & getDefault(0,fDefault,"BGL") & ">BGL - Bulgarian Lev</option>" & vbCrLf & _
				vbTab & "<option value=""BIF""" & getDefault(0,fDefault,"BIF") & ">BIF - Burundi Franc</option>" & vbCrLf & _
				vbTab & "<option value=""XOF""" & getDefault(0,fDefault,"XOF") & ">XOF - CFA Franc BCEAO</option>" & vbCrLf & _
				vbTab & "<option value=""XAF""" & getDefault(0,fDefault,"XAF") & ">XAF - CFA Franc BEAC</option>" & vbCrLf & _
				vbTab & "<option value=""XPF""" & getDefault(0,fDefault,"XPF") & ">XPF - CFP Franc</option>" & vbCrLf & _
				vbTab & "<option value=""KHR""" & getDefault(0,fDefault,"KHR") & ">KHR - Cambodian Riel</option>" & vbCrLf & _
				vbTab & "<option value=""CAD""" & getDefault(0,fDefault,"CAD") & ">CAD - Canadian Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""CVE""" & getDefault(0,fDefault,"CVE") & ">CVE - Cape Verde Escudo</option>" & vbCrLf & _
				vbTab & "<option value=""KYD""" & getDefault(0,fDefault,"KYD") & ">KYD - Cayman Islands Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""CLP""" & getDefault(0,fDefault,"CLP") & ">CLP - Chilean Peso</option>" & vbCrLf & _
				vbTab & "<option value=""CNY""" & getDefault(0,fDefault,"CNY") & ">CNY - Chinese Yuan Renminbi</option>" & vbCrLf & _
				vbTab & "<option value=""COP""" & getDefault(0,fDefault,"COP") & ">COP - Colombian Peso</option>" & vbCrLf & _
				vbTab & "<option value=""KMF""" & getDefault(0,fDefault,"KMF") & ">KMF - Comoros Franc</option>" & vbCrLf & _
				vbTab & "<option value=""CRC""" & getDefault(0,fDefault,"CRC") & ">CRC - Costa Rican Colon</option>" & vbCrLf & _
				vbTab & "<option value=""HRK""" & getDefault(0,fDefault,"HRK") & ">HRK - Croatian Kuna</option>" & vbCrLf & _
				vbTab & "<option value=""CUP""" & getDefault(0,fDefault,"CUP") & ">CUP - Cuban Peso</option>" & vbCrLf & _
				vbTab & "<option value=""CYP""" & getDefault(0,fDefault,"CYP") & ">CYP - Cyprus Pound</option>" & vbCrLf & _
				vbTab & "<option value=""CZK""" & getDefault(0,fDefault,"CZK") & ">CZK - Czech Koruna</option>" & vbCrLf & _
				vbTab & "<option value=""DKK""" & getDefault(0,fDefault,"DKK") & ">DKK - Danish Krone</option>" & vbCrLf & _
				vbTab & "<option value=""DJF""" & getDefault(0,fDefault,"DJF") & ">DJF - Djibouti Franc</option>" & vbCrLf & _
				vbTab & "<option value=""DOP""" & getDefault(0,fDefault,"DOP") & ">DOP - Dominican R. Peso</option>" & vbCrLf & _
				vbTab & "<option value=""NLG""" & getDefault(0,fDefault,"NLG") & ">NLG - Dutch Guilder</option>" & vbCrLf & _
				vbTab & "<option value=""XEU""" & getDefault(0,fDefault,"XEU") & ">XEU - ECU</option>" & vbCrLf & _
				vbTab & "<option value=""XCD""" & getDefault(0,fDefault,"XCD") & ">XCD - East Caribbean Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""ECS""" & getDefault(0,fDefault,"ECS") & ">ECS - Ecuador Sucre</option>" & vbCrLf & _
				vbTab & "<option value=""EGP""" & getDefault(0,fDefault,"EGP") & ">EGP - Egyptian Pound</option>" & vbCrLf & _
				vbTab & "<option value=""SVC""" & getDefault(0,fDefault,"SVC") & ">SVC - El Salvador Colon</option>" & vbCrLf & _
				vbTab & "<option value=""EEK""" & getDefault(0,fDefault,"EEK") & ">EEK - Estonian Kroon</option>" & vbCrLf & _
				vbTab & "<option value=""ETB""" & getDefault(0,fDefault,"ETB") & ">ETB - Ethiopian Birr</option>" & vbCrLf & _
				vbTab & "<option value=""EUR""" & getDefault(0,fDefault,"EUR") & ">EUR - Euro</option>" & vbCrLf & _
				vbTab & "<option value=""FKP""" & getDefault(0,fDefault,"FKP") & ">FKP - Falkland Islands Pound</option>" & vbCrLf & _
				vbTab & "<option value=""FJD""" & getDefault(0,fDefault,"FJD") & ">FJD - Fiji Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""FIM""" & getDefault(0,fDefault,"FIM") & ">FIM - Finnish Markka</option>" & vbCrLf & _
				vbTab & "<option value=""FRF""" & getDefault(0,fDefault,"FRF") & ">FRF - French Franc</option>" & vbCrLf & _
				vbTab & "<option value=""GMD""" & getDefault(0,fDefault,"GMD") & ">GMD - Gambian Dalasi</option>" & vbCrLf & _
				vbTab & "<option value=""DEM""" & getDefault(0,fDefault,"DEM") & ">DEM - German Mark</option>" & vbCrLf & _
				vbTab & "<option value=""GHC""" & getDefault(0,fDefault,"GHC") & ">GHC - Ghanaian Cedi</option>" & vbCrLf & _
				vbTab & "<option value=""GIP""" & getDefault(0,fDefault,"GIP") & ">GIP - Gibraltar Pound</option>" & vbCrLf & _
				vbTab & "<option value=""XAU""" & getDefault(0,fDefault,"XAU") & ">XAU - Gold (oz.)</option>" & vbCrLf & _
				vbTab & "<option value=""GRD""" & getDefault(0,fDefault,"GRD") & ">GRD - Greek Drachma</option>" & vbCrLf & _
				vbTab & "<option value=""GTQ""" & getDefault(0,fDefault,"GTQ") & ">GTQ - Guatemalan Quetzal</option>" & vbCrLf & _
				vbTab & "<option value=""GNF""" & getDefault(0,fDefault,"GNF") & ">GNF - Guinea Franc</option>" & vbCrLf & _
				vbTab & "<option value=""GYD""" & getDefault(0,fDefault,"GYD") & ">GYD - Guyanese Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""HTG""" & getDefault(0,fDefault,"HTG") & ">HTG - Haitian Gourde</option>" & vbCrLf & _
				vbTab & "<option value=""HNL""" & getDefault(0,fDefault,"HNL") & ">HNL - Honduran Lempira</option>" & vbCrLf & _
				vbTab & "<option value=""HKD""" & getDefault(0,fDefault,"HKD") & ">HKD - Hong Kong Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""HUF""" & getDefault(0,fDefault,"HUF") & ">HUF - Hungarian Forint</option>" & vbCrLf & _
				vbTab & "<option value=""ISK""" & getDefault(0,fDefault,"ISK") & ">ISK - Iceland Krona</option>" & vbCrLf & _
				vbTab & "<option value=""INR""" & getDefault(0,fDefault,"INR") & ">INR - Indian Rupee</option>" & vbCrLf & _
				vbTab & "<option value=""IDR""" & getDefault(0,fDefault,"IDR") & ">IDR - Indonesian Rupiah</option>" & vbCrLf & _
				vbTab & "<option value=""IRR""" & getDefault(0,fDefault,"IRR") & ">IRR - Iranian Rial</option>" & vbCrLf & _
				vbTab & "<option value=""IQD""" & getDefault(0,fDefault,"IQD") & ">IQD - Iraqi Dinar</option>" & vbCrLf & _
				vbTab & "<option value=""IEP""" & getDefault(0,fDefault,"IEP") & ">IEP - Irish Punt</option>" & vbCrLf & _
				vbTab & "<option value=""ILS""" & getDefault(0,fDefault,"ILS") & ">ILS - Israeli New Shekel</option>" & vbCrLf & _
				vbTab & "<option value=""ITL""" & getDefault(0,fDefault,"ITL") & ">ITL - Italian Lira</option>" & vbCrLf & _
				vbTab & "<option value=""JMD""" & getDefault(0,fDefault,"JMD") & ">JMD - Jamaican Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""JPY""" & getDefault(0,fDefault,"JPY") & ">JPY - Japanese Yen</option>" & vbCrLf & _
				vbTab & "<option value=""JOD""" & getDefault(0,fDefault,"JOD") & ">JOD - Jordanian Dinar</option>" & vbCrLf & _
				vbTab & "<option value=""KZT""" & getDefault(0,fDefault,"KZT") & ">KZT - Kazakhstan Tenge</option>" & vbCrLf & _
				vbTab & "<option value=""KES""" & getDefault(0,fDefault,"KES") & ">KES - Kenyan Shilling</option>" & vbCrLf & _
				vbTab & "<option value=""KWD""" & getDefault(0,fDefault,"KWD") & ">KWD - Kuwaiti Dinar</option>" & vbCrLf & _
				vbTab & "<option value=""LAK""" & getDefault(0,fDefault,"LAK") & ">LAK - Lao Kip</option>" & vbCrLf & _
				vbTab & "<option value=""LVL""" & getDefault(0,fDefault,"LVL") & ">LVL - Latvian Lats</option>" & vbCrLf & _
				vbTab & "<option value=""LBP""" & getDefault(0,fDefault,"LBP") & ">LBP - Lebanese Pound</option>" & vbCrLf & _
				vbTab & "<option value=""LSL""" & getDefault(0,fDefault,"LSL") & ">LSL - Lesotho Loti</option>" & vbCrLf & _
				vbTab & "<option value=""LRD""" & getDefault(0,fDefault,"LRD") & ">LRD - Liberian Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""LYD""" & getDefault(0,fDefault,"LYD") & ">LYD - Libyan Dinar</option>" & vbCrLf & _
				vbTab & "<option value=""LTL""" & getDefault(0,fDefault,"LTL") & ">LTL - Lithuanian Litas</option>" & vbCrLf & _
				vbTab & "<option value=""LUF""" & getDefault(0,fDefault,"LUF") & ">LUF - Luxembourg Franc</option>" & vbCrLf & _
				vbTab & "<option value=""MOP""" & getDefault(0,fDefault,"MOP") & ">MOP - Macau Pataca</option>" & vbCrLf & _
				vbTab & "<option value=""MGF""" & getDefault(0,fDefault,"MGF") & ">MGF - Malagasy Franc</option>" & vbCrLf & _
				vbTab & "<option value=""MWK""" & getDefault(0,fDefault,"MWK") & ">MWK - Malawi Kwacha</option>" & vbCrLf & _
				vbTab & "<option value=""MYR""" & getDefault(0,fDefault,"MYR") & ">MYR - Malaysian Ringgit</option>" & vbCrLf & _
				vbTab & "<option value=""MVR""" & getDefault(0,fDefault,"MVR") & ">MVR - Maldive Rufiyaa</option>" & vbCrLf & _
				vbTab & "<option value=""MTL""" & getDefault(0,fDefault,"MTL") & ">MTL - Maltese Lira</option>" & vbCrLf & _
				vbTab & "<option value=""MRO""" & getDefault(0,fDefault,"MRO") & ">MRO - Mauritanian Ouguiya</option>" & vbCrLf & _
				vbTab & "<option value=""MUR""" & getDefault(0,fDefault,"MUR") & ">MUR - Mauritius Rupee</option>" & vbCrLf & _
				vbTab & "<option value=""MXN""" & getDefault(0,fDefault,"MXN") & ">MXN - Mexican Peso</option>" & vbCrLf & _
				vbTab & "<option value=""MNT""" & getDefault(0,fDefault,"MNT") & ">MNT - Mongolian Tugrik</option>" & vbCrLf & _
				vbTab & "<option value=""MAD""" & getDefault(0,fDefault,"MAD") & ">MAD - Moroccan Dirham</option>" & vbCrLf & _
				vbTab & "<option value=""MZM""" & getDefault(0,fDefault,"MZM") & ">MZM - Mozambique Metical</option>" & vbCrLf & _
				vbTab & "<option value=""MMK""" & getDefault(0,fDefault,"MMK") & ">MMK - Myanmar Kyat</option>" & vbCrLf & _
				vbTab & "<option value=""ANG""" & getDefault(0,fDefault,"ANG") & ">ANG - NL Antillian Guilder</option>" & vbCrLf & _
				vbTab & "<option value=""NAD""" & getDefault(0,fDefault,"NAD") & ">NAD - Namibia Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""NPR""" & getDefault(0,fDefault,"NPR") & ">NPR - Nepalese Rupee</option>" & vbCrLf & _
				vbTab & "<option value=""NZD""" & getDefault(0,fDefault,"NZD") & ">NZD - New Zealand Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""NIO""" & getDefault(0,fDefault,"NIO") & ">NIO - Nicaraguan Cordoba Oro</option>" & vbCrLf & _
				vbTab & "<option value=""NGN""" & getDefault(0,fDefault,"NGN") & ">NGN - Nigerian Naira</option>" & vbCrLf & _
				vbTab & "<option value=""KPW""" & getDefault(0,fDefault,"KPW") & ">KPW - North Korean Won</option>" & vbCrLf & _
				vbTab & "<option value=""NOK""" & getDefault(0,fDefault,"NOK") & ">NOK - Norwegian Kroner</option>" & vbCrLf & _
				vbTab & "<option value=""OMR""" & getDefault(0,fDefault,"OMR") & ">OMR - Omani Rial</option>" & vbCrLf & _
				vbTab & "<option value=""PKR""" & getDefault(0,fDefault,"PKR") & ">PKR - Pakistan Rupee</option>" & vbCrLf & _
				vbTab & "<option value=""XPD""" & getDefault(0,fDefault,"XPD") & ">XPD - Palladium (oz.)</option>" & vbCrLf & _
				vbTab & "<option value=""PAB""" & getDefault(0,fDefault,"PAB") & ">PAB - Panamanian Balboa</option>" & vbCrLf & _
				vbTab & "<option value=""PGK""" & getDefault(0,fDefault,"PGK") & ">PGK - Papua New Guinea Kina</option>" & vbCrLf & _
				vbTab & "<option value=""PYG""" & getDefault(0,fDefault,"PYG") & ">PYG - Paraguay Guarani</option>" & vbCrLf & _
				vbTab & "<option value=""PEN""" & getDefault(0,fDefault,"PEN") & ">PEN - Peruvian Nuevo Sol</option>" & vbCrLf & _
				vbTab & "<option value=""PHP""" & getDefault(0,fDefault,"PHP") & ">PHP - Philippine Peso</option>" & vbCrLf & _
				vbTab & "<option value=""XPT""" & getDefault(0,fDefault,"XPT") & ">XPT - Platinum (oz.)</option>" & vbCrLf & _
				vbTab & "<option value=""PLN""" & getDefault(0,fDefault,"PLN") & ">PLN - Polish Zloty</option>" & vbCrLf & _
				vbTab & "<option value=""PTE""" & getDefault(0,fDefault,"PTE") & ">PTE - Portuguese Escudo</option>" & vbCrLf & _
				vbTab & "<option value=""QAR""" & getDefault(0,fDefault,"QAR") & ">QAR - Qatari Rial</option>" & vbCrLf & _
				vbTab & "<option value=""ROL""" & getDefault(0,fDefault,"ROL") & ">ROL - Romanian Lei</option>" & vbCrLf & _
				vbTab & "<option value=""RUB""" & getDefault(0,fDefault,"RUB") & ">RUB - Russian Rouble</option>" & vbCrLf & _
				vbTab & "<option value=""WST""" & getDefault(0,fDefault,"WST") & ">WST - Samoan Tala</option>" & vbCrLf & _
				vbTab & "<option value=""STD""" & getDefault(0,fDefault,"STD") & ">STD - Sao Tome/Principe Dobra</option>" & vbCrLf & _
				vbTab & "<option value=""SAR""" & getDefault(0,fDefault,"SAR") & ">SAR - Saudi Riyal</option>" & vbCrLf & _
				vbTab & "<option value=""SCR""" & getDefault(0,fDefault,"SCR") & ">SCR - Seychelles Rupee</option>" & vbCrLf & _
				vbTab & "<option value=""SLL""" & getDefault(0,fDefault,"SLL") & ">SLL - Sierra Leone Leone</option>" & vbCrLf & _
				vbTab & "<option value=""XAG""" & getDefault(0,fDefault,"XAG") & ">XAG - Silver (oz.)</option>" & vbCrLf & _
				vbTab & "<option value=""SGD""" & getDefault(0,fDefault,"SGD") & ">SGD - Singapore Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""SKK""" & getDefault(0,fDefault,"SKK") & ">SKK - Slovak Koruna</option>" & vbCrLf & _
				vbTab & "<option value=""SIT""" & getDefault(0,fDefault,"SIT") & ">SIT - Slovenian Tolar</option>" & vbCrLf & _
				vbTab & "<option value=""SBD""" & getDefault(0,fDefault,"SBD") & ">SBD - Solomon Islands Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""SOS""" & getDefault(0,fDefault,"SOS") & ">SOS - Somali Shilling</option>" & vbCrLf & _
				vbTab & "<option value=""ZAR""" & getDefault(0,fDefault,"ZAR") & ">ZAR - South African Rand</option>" & vbCrLf & _
				vbTab & "<option value=""KRW""" & getDefault(0,fDefault,"KRW") & ">KRW - South-Korean Won</option>" & vbCrLf & _
				vbTab & "<option value=""ESP""" & getDefault(0,fDefault,"ESP") & ">ESP - Spanish Peseta</option>" & vbCrLf & _
				vbTab & "<option value=""LKR""" & getDefault(0,fDefault,"LKR") & ">LKR - Sri Lanka Rupee</option>" & vbCrLf & _
				vbTab & "<option value=""SHP""" & getDefault(0,fDefault,"SHP") & ">SHP - St. Helena Pound</option>" & vbCrLf & _
				vbTab & "<option value=""SDD""" & getDefault(0,fDefault,"SDD") & ">SDD - Sudanese Dinar</option>" & vbCrLf & _
				vbTab & "<option value=""SDP""" & getDefault(0,fDefault,"SDP") & ">SDP - Sudanese Pound</option>" & vbCrLf & _
				vbTab & "<option value=""SRG""" & getDefault(0,fDefault,"SRG") & ">SRG - Suriname Guilder</option>" & vbCrLf & _
				vbTab & "<option value=""SZL""" & getDefault(0,fDefault,"SZL") & ">SZL - Swaziland Lilangeni</option>" & vbCrLf & _
				vbTab & "<option value=""SEK""" & getDefault(0,fDefault,"SEK") & ">SEK - Swedish Krona</option>" & vbCrLf & _
				vbTab & "<option value=""CHF""" & getDefault(0,fDefault,"CHF") & ">CHF - Swiss Franc</option>" & vbCrLf & _
				vbTab & "<option value=""SYP""" & getDefault(0,fDefault,"SYP") & ">SYP - Syrian Pound</option>" & vbCrLf & _
				vbTab & "<option value=""TWD""" & getDefault(0,fDefault,"TWD") & ">TWD - Taiwan Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""TZS""" & getDefault(0,fDefault,"TZS") & ">TZS - Tanzanian Shilling</option>" & vbCrLf & _
				vbTab & "<option value=""THB""" & getDefault(0,fDefault,"THB") & ">THB - Thai Baht</option>" & vbCrLf & _
				vbTab & "<option value=""TOP""" & getDefault(0,fDefault,"TOP") & ">TOP - Tonga Pa'anga</option>" & vbCrLf & _
				vbTab & "<option value=""TTD""" & getDefault(0,fDefault,"TTD") & ">TTD - Trinidad/Tobago Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""TND""" & getDefault(0,fDefault,"TND") & ">TND - Tunisian Dinar</option>" & vbCrLf & _
				vbTab & "<option value=""TRL""" & getDefault(0,fDefault,"TRL") & ">TRL - Turkish Lira</option>" & vbCrLf & _
				vbTab & "<option value=""UGS""" & getDefault(0,fDefault,"UGS") & ">UGS - Uganda Shilling</option>" & vbCrLf & _
				vbTab & "<option value=""UAH""" & getDefault(0,fDefault,"UAH") & ">UAH - Ukraine Hryvnia</option>" & vbCrLf & _
				vbTab & "<option value=""UYP""" & getDefault(0,fDefault,"UYP") & ">UYP - Uruguayan Peso</option>" & vbCrLf & _
				vbTab & "<option value=""USD""" & getDefault(0,fDefault,"USD") & ">USD - US Dollar</option>" & vbCrLf & _
				vbTab & "<option value=""AED""" & getDefault(0,fDefault,"AED") & ">AED - Utd. Arab Emir. Dirham</option>" & vbCrLf & _
				vbTab & "<option value=""VUV""" & getDefault(0,fDefault,"VUV") & ">VUV - Vanuatu Vatu</option>" & vbCrLf & _
				vbTab & "<option value=""VEB""" & getDefault(0,fDefault,"VEB") & ">VEB - Venezuelan Bolivar</option>" & vbCrLf & _
				vbTab & "<option value=""VND""" & getDefault(0,fDefault,"VND") & ">VND - Vietnamese Dong</option>" & vbCrLf & _
				vbTab & "<option value=""YUN""" & getDefault(0,fDefault,"YUN") & ">YUN - Yugoslav Dinar</option>" & vbCrLf & _
				vbTab & "<option value=""ZMK""" & getDefault(0,fDefault,"ZMK") & ">ZMK - Zambian Kwacha</option>" & vbCrLf & _
				vbTab & "<option value=""ZWD""" & getDefault(0,fDefault,"ZWD") & ">ZWD - Zimbabwe Dollar</option>" & vbCrLf & _
			"</select>" & vbCrLf

End Function
%>